DTYPES_SIMPLE = ["cd", "cf", "d", "f", "i64", "u64", "i32", "u32", "i16", "u16", "b"]
DTYPES_FULL = ["cytnx_complex128", "cytnx_complex64", "cytnx_double", "cytnx_float", "cytnx_int64", "cytnx_uint64", "cytnx_int32", "cytnx_uint32", "cytnx_int16", "cytnx_uint32", "bool"]
for i in range(11):
    for j in range(11):
        print("\
  // This function is generated by python script\n\
  void Kron_internal_"+DTYPES_SIMPLE[i]+"t"+DTYPES_SIMPLE[j]+"(\n\
    boost::intrusive_ptr<Storage_base> &out, const boost::intrusive_ptr<Storage_base> &Lin,\n\
    const boost::intrusive_ptr<Storage_base> &Rin, const std::vector<cytnx_uint64> &shape1,\n\
    const std::vector<cytnx_uint64> &shape2) {\n\
    Kron_general<"+DTYPES_FULL[i]+","+DTYPES_FULL[j]+">(out, Lin, Rin, shape1, shape2);\n\
  }\n")
