coverage:
  status:
    project:
      default:
        target: auto
        threshold: 100%
    patch:
      default:
        target: auto
        threshold: 100%
ignore:
  - "tests"
  - "bm_tests"
  - "pybind"
  - "cytnx"
  - "example"
