{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: cytnx
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  script_env:
    # Refer to : https://github.com/ccache/ccache/discussions/821#discussioncomment-521209
    - CCACHE_NOHASHDIR=1
    - CCACHE_COMPILERCHECK=content
    - CCACHE_DIR
    - CCACHE_MAXSIZE
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER

requirements:
  build:
    - ccache
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - setuptools
    - pybind11
    - boost >=1.82.0
    - blas=*=mkl
    - gtest
  run:
    - python
    - numpy >=1.18
    - boost >=1.82.0
    - python-graphviz
    - graphviz
    - blas=*=mkl
    - beartype

test:
  requires:
    - gtest
