{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: cytnx
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  script_env:
    # Refer to : https://github.com/ccache/ccache/discussions/821#discussioncomment-521209
    - CCACHE_NOHASHDIR=1
    - CCACHE_COMPILERCHECK=content
    - CCACHE_DIR
    - CCACHE_MAXSIZE
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER


requirements:
  build:
    - ccache
    - "python {{ python }}"
    - "numpy >=1.18"
    - "cmake"
    - "make"
    - "pybind11"
    - "boost >=1.82.0"
    # - "libboost"
    - "mkl >=2019"
    - "mkl-include >=2019"
    - "llvm-openmp"
    - "setuptools"
    - "python-graphviz"
    - "graphviz"
    - "blas * mkl"
    - "beartype"
    - "gtest"
    - '{{ compiler("c")}}'
    - '{{ compiler("cxx")}}'

  host:
    - "python"
    - "numpy >=1.18"
    - "boost >=1.82.0"
    # - "libboost"
    - "make"
    - "mkl >=2019"
    - "mkl-include >=2019"
    - "mkl-service"
    - "llvm-openmp"
    - "setuptools"
    - "python-graphviz"
    - "graphviz"
    - "blas * mkl"
    - "beartype"
    - "gtest"
    - '{{ compiler("c")}}'
    - '{{ compiler("cxx")}}'

  run:
    - "python"
    - "numpy >=1.18"
    - "boost >=1.82.0"
    # - "libboost"
    - "mkl >=2019"
    - "mkl-include >=2019"
    - "mkl-service"
    - "llvm-openmp"
    - "setuptools"
    - "python-graphviz"
    - "graphviz"
    - "blas * mkl"
    - "beartype"
    - "cmake"
    - "make"
    - "pybind11"
    - "gtest"
    - '{{ compiler("c")}}'
    - '{{ compiler("cxx")}}'

about:
