package:
  name: cytnx_cuda_37
  version: "0.5.5a"

source:
  path: ../

build:
  number: 2


requirements:
  build:
    - python 3.7
    - numpy >=1.18
    - cmake  
    - pybind11 
    - boost 
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - cudatoolkit >=10
    - python-graphviz
    - graphviz
    - blas * mkl
    - {{ compiler("c")}}
    - {{ compiler("cxx")}}

  host:
    - python 3.7
    - numpy >=1.18
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - cudatoolkit >=10
    - python-graphviz
    - graphviz
    - blas * mkl

  run:
    - python 3.7
    - numpy >=1.18
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - cudatoolkit >=10
    - python-graphviz
    - graphviz
    - blas * mkl

about:
