package:
  name: cytnx_cuda_37
  version: "0.4"

source:
  path: ../

build:
  noarch: generic
  number: 0


requirements:
  build:
    - python 3.7
    - cmake  
    - pybind11 
    - boost
    - mkl
    - mkl-include
    - intel-openmp
    - setuptools
    - cudatoolkit
    - {{ compiler("c")}}
    - {{ compiler("cxx")}}

  host:
    - python 3.7
    - boost
    - mkl
    - mkl-include
    - intel-openmp
    - setuptools
    - cudatoolkit
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}

  run:
    - python 3.7
    - boost
    - mkl
    - mkl-include
    - intel-openmp
    - setuptools
    - cudatoolkit
    - python-graphviz
    - {{ compiler("c")}}
    - {{ compiler("cxx")}}

about:
