#include "Outer_internal.hpp"
#include "Ger_internal.hpp"
#include "../utils_internal_interface.hpp"
#include "utils/complex_arithmetic.hpp"
#include "backend/lapack_wrapper.hpp"

#ifdef UNI_OMP
  #include <omp.h>
#endif

// change to *ger

namespace cytnx {

  namespace linalg_internal {

    template <class TO, class T1, class T2>
    void Outer_general(boost::intrusive_ptr<Storage_base> &out,
                       const boost::intrusive_ptr<Storage_base> &Lin,
                       const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                       const cytnx_uint64 &j2) {
      TO *_out = (TO *)out->Mem;
      T1 *_Lin = (T1 *)Lin->Mem;
      T2 *_Rin = (T2 *)Rin->Mem;

#ifdef UNI_OMP
  #pragma omp parallel for schedule(dynamic)
#endif
      for (unsigned long long r = 0; r < j1 * j2; r++) {
        _out[r] = _Lin[cytnx_uint64(r / j2)] * _Rin[(r % j2)];
      }
    }

    // This function is generated by python script
    void Outer_internal_cdtcd(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cdtcf(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cdtd(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cdtf(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cdti64(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cdtu64(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cdti32(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cdtu32(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cdti16(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cdtu16(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cdtb(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex128, bool>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cftcd(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_complex64, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cftcf(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_complex64, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cftd(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_complex64, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cftf(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_complex64, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cfti64(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_complex64, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cftu64(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_complex64, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cfti32(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_complex64, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cftu32(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_complex64, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cfti16(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_complex64, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cftu16(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_complex64, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_cftb(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_complex64, bool>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dtcd(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_double, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dtcf(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_double, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dtd(boost::intrusive_ptr<Storage_base> &out,
                            const boost::intrusive_ptr<Storage_base> &Lin,
                            const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                            const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_double, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dtf(boost::intrusive_ptr<Storage_base> &out,
                            const boost::intrusive_ptr<Storage_base> &Lin,
                            const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                            const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_double, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dti64(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_double, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dtu64(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_double, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dti32(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_double, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dtu32(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_double, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dti16(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_double, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dtu16(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_double, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_dtb(boost::intrusive_ptr<Storage_base> &out,
                            const boost::intrusive_ptr<Storage_base> &Lin,
                            const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                            const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_double, bool>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_ftcd(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_float, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_ftcf(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_float, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_ftd(boost::intrusive_ptr<Storage_base> &out,
                            const boost::intrusive_ptr<Storage_base> &Lin,
                            const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                            const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_float, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_ftf(boost::intrusive_ptr<Storage_base> &out,
                            const boost::intrusive_ptr<Storage_base> &Lin,
                            const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                            const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_float, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_fti64(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_float, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_ftu64(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_float, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_fti32(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_float, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_ftu32(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_float, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_fti16(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_float, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_ftu16(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_float, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_ftb(boost::intrusive_ptr<Storage_base> &out,
                            const boost::intrusive_ptr<Storage_base> &Lin,
                            const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                            const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_float, bool>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64tcd(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_int64, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64tcf(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_int64, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64td(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_int64, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64tf(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_int64, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64ti64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int64, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64tu64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int64, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64ti32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int64, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64tu32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int64, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64ti16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int64, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64tu16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int64, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i64tb(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int64, bool>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64tcd(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_uint64, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64tcf(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_uint64, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64td(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_uint64, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64tf(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_uint64, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64ti64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_uint64, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64tu64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint64, cytnx_uint64, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64ti32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_uint64, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64tu32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint64, cytnx_uint64, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64ti16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_uint64, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64tu16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint64, cytnx_uint64, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u64tb(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint64, cytnx_uint64, bool>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32tcd(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_int32, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32tcf(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_int32, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32td(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_int32, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32tf(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_int32, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32ti64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int32, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32tu64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int32, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32ti32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, cytnx_int32, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32tu32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, cytnx_int32, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32ti16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, cytnx_int32, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32tu16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, cytnx_int32, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i32tb(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, cytnx_int32, bool>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32tcd(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_uint32, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32tcf(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_uint32, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32td(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_uint32, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32tf(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_uint32, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32ti64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_uint32, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32tu64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint64, cytnx_uint32, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32ti32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, cytnx_uint32, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32tu32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint32, cytnx_uint32, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32ti16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, cytnx_uint32, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32tu16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint32, cytnx_uint32, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u32tb(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint32, cytnx_uint32, bool>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16tcd(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_int16, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16tcf(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_int16, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16td(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_int16, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16tf(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_int16, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16ti64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int16, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16tu64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_int16, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16ti32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, cytnx_int16, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16tu32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, cytnx_int16, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16ti16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int16, cytnx_int16, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16tu16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int16, cytnx_int16, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_i16tb(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_int16, cytnx_int16, bool>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16tcd(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, cytnx_uint16, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16tcf(boost::intrusive_ptr<Storage_base> &out,
                               const boost::intrusive_ptr<Storage_base> &Lin,
                               const boost::intrusive_ptr<Storage_base> &Rin,
                               const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, cytnx_uint16, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16td(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, cytnx_uint16, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16tf(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, cytnx_uint16, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16ti64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, cytnx_uint16, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16tu64(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint64, cytnx_uint16, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16ti32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, cytnx_uint16, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16tu32(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint32, cytnx_uint16, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16ti16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_int16, cytnx_uint16, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16tu16(boost::intrusive_ptr<Storage_base> &out,
                                const boost::intrusive_ptr<Storage_base> &Lin,
                                const boost::intrusive_ptr<Storage_base> &Rin,
                                const cytnx_uint64 &j1, const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint16, cytnx_uint16, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_u16tb(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint16, cytnx_uint16, bool>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_btcd(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex128, bool, cytnx_complex128>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_btcf(boost::intrusive_ptr<Storage_base> &out,
                             const boost::intrusive_ptr<Storage_base> &Lin,
                             const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                             const cytnx_uint64 &j2) {
      Outer_general<cytnx_complex64, bool, cytnx_complex64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_btd(boost::intrusive_ptr<Storage_base> &out,
                            const boost::intrusive_ptr<Storage_base> &Lin,
                            const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                            const cytnx_uint64 &j2) {
      Outer_general<cytnx_double, bool, cytnx_double>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_btf(boost::intrusive_ptr<Storage_base> &out,
                            const boost::intrusive_ptr<Storage_base> &Lin,
                            const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                            const cytnx_uint64 &j2) {
      Outer_general<cytnx_float, bool, cytnx_float>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_bti64(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_int64, bool, cytnx_int64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_btu64(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint64, bool, cytnx_uint64>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_bti32(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_int32, bool, cytnx_int32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_btu32(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint32, bool, cytnx_uint32>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_bti16(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_int16, bool, cytnx_int16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_btu16(boost::intrusive_ptr<Storage_base> &out,
                              const boost::intrusive_ptr<Storage_base> &Lin,
                              const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                              const cytnx_uint64 &j2) {
      Outer_general<cytnx_uint16, bool, cytnx_uint16>(out, Lin, Rin, j1, j2);
    }

    // This function is generated by python script
    void Outer_internal_btb(boost::intrusive_ptr<Storage_base> &out,
                            const boost::intrusive_ptr<Storage_base> &Lin,
                            const boost::intrusive_ptr<Storage_base> &Rin, const cytnx_uint64 &j1,
                            const cytnx_uint64 &j2) {
      Outer_general<bool, bool, bool>(out, Lin, Rin, j1, j2);
    }

  }  // namespace linalg_internal
}  // namespace cytnx
