package:
  name: cytnx_36
  version: "0.5.2.1a"

source:
  path: ../

build:
  noarch: generic
  number: 0


requirements:
  build:
    - python 3.6
    - cmake  
    - pybind11 
    - boost
    - mkl
    - mkl-include
    - intel-openmp
    - setuptools
    - python-graphviz
    - graphviz
    - {{ compiler("c")}}
    - {{ compiler("cxx")}}

  host:
    - python 3.6
    - boost
    - mkl
    - mkl-include
    - intel-openmp
    - setuptools
    - python-graphviz
    - graphviz

  run:
    - python 3.6
    - boost
    - mkl
    - mkl-include
    - intel-openmp
    - setuptools
    - python-graphviz
    - graphviz

about:
