package:
  name: cytnx_36
  version: "0.5.2a"

source:
  path: ../

build:
  noarch: generic
  number: 1


requirements:
  build:
    - python 3.6
    - numpy >=1.18
    - cmake  
    - pybind11 
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - python-graphviz
    - graphviz
    - blas * mkl
    - {{ compiler("c")}}
    - {{ compiler("cxx")}}

  host:
    - python 3.6
    - numpy >=1.18
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - python-graphviz
    - graphviz
    - blas * mkl

  run:
    - python 3.6
    - numpy >=1.18
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - python-graphviz
    - graphviz
    - blas * mkl

about:
