package:
  name: cytnx_cuda_38
  version: "0.5.6a"

source:
  path: ../

build:
  number: 0


requirements:
  build:
    - python 3.8
    - numpy >=1.18
    - cmake  
    - pybind11 
    - boost 
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - cudatoolkit >=10
    - python-graphviz
    - graphviz
    - blas * mkl
    - {{ compiler("c")}}
    - {{ compiler("cxx")}}

  host:
    - python 3.8
    - numpy >=1.18
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - cudatoolkit >=10
    - python-graphviz
    - graphviz
    - blas * mkl

  run:
    - python 3.8
    - numpy >=1.18
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - cudatoolkit >=10
    - python-graphviz
    - graphviz
    - blas * mkl

about:
