"""
linear algebra related.
"""
from __future__ import annotations
import collections.abc
import cytnx.cytnx
import numpy
import typing
__all__: list[str] = ['Abs', 'Abs_', 'Arnoldi', 'Conj', 'Conj_', 'Det', 'Diag', 'Directsum', 'Dot', 'Eig', 'Eigh', 'Exp', 'ExpH', 'ExpM', 'Exp_', 'Expf', 'Expf_', 'Gemm', 'Gemm_', 'Ger', 'Gesvd', 'Gesvd_truncate', 'Hosvd', 'Inv', 'InvM', 'InvM_', 'Inv_', 'Kron', 'Lanczos', 'Lanczos_Exp', 'Lstsq', 'Matmul', 'Matmul_dg', 'Max', 'Min', 'Norm', 'Outer', 'Pow', 'Pow_', 'Qdr', 'Qr', 'Rand_isometry', 'Rsvd', 'Sum', 'Svd', 'Svd_truncate', 'Tensordot', 'Tensordot_dg', 'Trace', 'Tridiag', 'Vectordot', 'norm']
def Abs(Tn: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
def Abs_(Tn: cytnx.cytnx.Tensor) -> None:
    ...
@typing.overload
def Arnoldi(Hop: cytnx.cytnx.LinOp, Tin: cytnx.cytnx.Tensor, which: str = 'LM', Maxiter: typing.SupportsInt | typing.SupportsIndex = 10000, CvgCrit: typing.SupportsFloat | typing.SupportsIndex = 0, k: typing.SupportsInt | typing.SupportsIndex = 1, is_V: bool = True, ncv: typing.SupportsInt | typing.SupportsIndex = 0, verbose: bool = False) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Arnoldi(Hop: cytnx.cytnx.LinOp, Tin: cytnx.cytnx.UniTensor, which: str = 'LM', Maxiter: typing.SupportsInt | typing.SupportsIndex = 10000, CvgCrit: typing.SupportsFloat | typing.SupportsIndex = 0, k: typing.SupportsInt | typing.SupportsIndex = 1, is_V: bool = True, ncv: typing.SupportsInt | typing.SupportsIndex = 0, verbose: bool = False) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Conj(Tin: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Conj(Tin: cytnx.cytnx.UniTensor) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def Conj_(Tin: cytnx.cytnx.Tensor) -> None:
    ...
@typing.overload
def Conj_(Tin: cytnx.cytnx.UniTensor) -> None:
    ...
def Det(Tin: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
def Diag(Tin: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
def Directsum(T1: cytnx.cytnx.Tensor, T2: cytnx.cytnx.Tensor, shared_axes: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> cytnx.cytnx.Tensor:
    ...
def Dot(T1: cytnx.cytnx.Tensor, T2: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Eig(Tin: cytnx.cytnx.Tensor, is_V: bool = True, row_v: bool = False) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Eig(Tin: cytnx.cytnx.UniTensor, is_V: bool = True, row_v: bool = False) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Eigh(Tin: cytnx.cytnx.Tensor, is_V: bool = True, row_v: bool = False) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Eigh(Tin: cytnx.cytnx.UniTensor, is_V: bool = True, row_v: bool = False) -> list[cytnx.cytnx.UniTensor]:
    ...
def Exp(Tin: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: numpy.float32, b: numpy.float32 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: numpy.complex64, b: numpy.complex64 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: numpy.int64, b: numpy.int64 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: numpy.uint64, b: numpy.uint64 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: numpy.int32, b: numpy.int32 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: numpy.uint32, b: numpy.uint32 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: numpy.int16, b: numpy.int16 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: numpy.uint16, b: numpy.uint16 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: int, b: int = 0) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor, a: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex, b: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex = 0j) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.UniTensor) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: numpy.float32, b: numpy.float32 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: numpy.complex64, b: numpy.complex64 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: numpy.int64, b: numpy.int64 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: numpy.uint64, b: numpy.uint64 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: numpy.int32, b: numpy.int32 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: numpy.uint32, b: numpy.uint32 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: numpy.int16, b: numpy.int16 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: numpy.uint16, b: numpy.uint16 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: int, b: int = 0) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor, a: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex, b: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex = 0j) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpH(Tin: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: numpy.float32, b: numpy.float32 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: numpy.complex64, b: numpy.complex64 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: numpy.int64, b: numpy.int64 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: numpy.uint64, b: numpy.uint64 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: numpy.int32, b: numpy.int32 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: numpy.uint32, b: numpy.uint32 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: numpy.int16, b: numpy.int16 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: numpy.uint16, b: numpy.uint16 = ...) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: int, b: int = 0) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor, a: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex, b: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex = 0j) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.UniTensor) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: numpy.float32, b: numpy.float32 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: numpy.complex64, b: numpy.complex64 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: numpy.int64, b: numpy.int64 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: numpy.uint64, b: numpy.uint64 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: numpy.int32, b: numpy.int32 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: numpy.uint32, b: numpy.uint32 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: numpy.int16, b: numpy.int16 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: numpy.uint16, b: numpy.uint16 = ...) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: int, b: int = 0) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: typing.SupportsFloat | typing.SupportsIndex, b: typing.SupportsFloat | typing.SupportsIndex = 0.0) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor, a: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex, b: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex = 0j) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def ExpM(Tin: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
def Exp_(Tio: cytnx.cytnx.Tensor) -> None:
    ...
def Expf(Tio: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
def Expf_(Tio: cytnx.cytnx.Tensor) -> None:
    ...
@typing.overload
def Gemm(a: typing.SupportsFloat | typing.SupportsIndex, x: cytnx.cytnx.Tensor, y: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Gemm(a: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex, x: cytnx.cytnx.Tensor, y: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Gemm_(a: typing.SupportsFloat | typing.SupportsIndex, x: cytnx.cytnx.Tensor, y: cytnx.cytnx.Tensor, b: typing.SupportsFloat | typing.SupportsIndex, c: cytnx.cytnx.Tensor) -> None:
    ...
@typing.overload
def Gemm_(a: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex, x: cytnx.cytnx.Tensor, y: cytnx.cytnx.Tensor, b: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex, c: cytnx.cytnx.Tensor) -> None:
    ...
@typing.overload
def Ger(x: cytnx.cytnx.Tensor, y: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Ger(x: cytnx.cytnx.Tensor, y: cytnx.cytnx.Tensor, a: typing.SupportsFloat | typing.SupportsIndex) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Ger(x: cytnx.cytnx.Tensor, y: cytnx.cytnx.Tensor, a: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Gesvd(Tin: cytnx.cytnx.Tensor, is_U: bool = True, is_vT: bool = True) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Gesvd(Tin: cytnx.cytnx.UniTensor, is_U: bool = True, is_vT: bool = True) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Gesvd_truncate(Tin: cytnx.cytnx.Tensor, keepdim: typing.SupportsInt | typing.SupportsIndex, err: typing.SupportsFloat | typing.SupportsIndex = 0.0, is_U: bool = True, is_vT: bool = True, return_err: typing.SupportsInt | typing.SupportsIndex = 0, mindim: typing.SupportsInt | typing.SupportsIndex = 1) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Gesvd_truncate(Tin: cytnx.cytnx.UniTensor, keepdim: typing.SupportsInt | typing.SupportsIndex, err: typing.SupportsFloat | typing.SupportsIndex = 0, is_U: bool = True, is_vT: bool = True, return_err: typing.SupportsInt | typing.SupportsIndex = 0, mindim: typing.SupportsInt | typing.SupportsIndex = 1) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Gesvd_truncate(Tin: cytnx.cytnx.UniTensor, keepdim: typing.SupportsInt | typing.SupportsIndex, min_blockdim: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], err: typing.SupportsFloat | typing.SupportsIndex = 0, is_U: bool = True, is_vT: bool = True, return_err: typing.SupportsInt | typing.SupportsIndex = 0, mindim: typing.SupportsInt | typing.SupportsIndex = 1) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Hosvd(Tn: cytnx.cytnx.Tensor, mode: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], is_core: bool = True, is_Ls: bool = False, truncate_dim: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = []) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Hosvd(Tn: cytnx.cytnx.UniTensor, mode: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], is_core: bool = True, is_Ls: bool = False, truncate_dim: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex] = []) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Inv(Tin: cytnx.cytnx.UniTensor, clip: typing.SupportsFloat | typing.SupportsIndex = -1) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def Inv(Tin: cytnx.cytnx.Tensor, clip: typing.SupportsFloat | typing.SupportsIndex = -1) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def InvM(Tin: cytnx.cytnx.UniTensor) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def InvM(Tin: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def InvM_(Tio: cytnx.cytnx.UniTensor) -> None:
    ...
@typing.overload
def InvM_(Tio: cytnx.cytnx.Tensor) -> None:
    ...
@typing.overload
def Inv_(Tin: cytnx.cytnx.UniTensor, clip: typing.SupportsFloat | typing.SupportsIndex = -1) -> None:
    ...
@typing.overload
def Inv_(Tin: cytnx.cytnx.Tensor, clip: typing.SupportsFloat | typing.SupportsIndex = -1) -> None:
    ...
def Kron(T1: cytnx.cytnx.Tensor, T2: cytnx.cytnx.Tensor, Tl_pad_left: bool = False, Tr_pad_left: bool = False) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Lanczos(Hop: cytnx.cytnx.LinOp, Tin: cytnx.cytnx.Tensor, method: str, CvgCrit: typing.SupportsFloat | typing.SupportsIndex = 1e-14, Maxiter: typing.SupportsInt | typing.SupportsIndex = 10000, k: typing.SupportsInt | typing.SupportsIndex = 1, is_V: bool = True, is_row: bool = False, max_krydim: typing.SupportsInt | typing.SupportsIndex = 0, verbose: bool = False) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Lanczos(Hop: cytnx.cytnx.LinOp, Tin: cytnx.cytnx.UniTensor, method: str, CvgCrit: typing.SupportsFloat | typing.SupportsIndex = 1e-14, Maxiter: typing.SupportsInt | typing.SupportsIndex = 10000, k: typing.SupportsInt | typing.SupportsIndex = 1, is_V: bool = True, is_row: bool = False, max_krydim: typing.SupportsInt | typing.SupportsIndex = 0, verbose: bool = False) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Lanczos(Hop: cytnx.cytnx.LinOp, Tin: cytnx.cytnx.Tensor, which: str = 'SA', Maxiter: typing.SupportsInt | typing.SupportsIndex = 10000, CvgCrit: typing.SupportsFloat | typing.SupportsIndex = 0, k: typing.SupportsInt | typing.SupportsIndex = 1, is_V: bool = True, ncv: typing.SupportsInt | typing.SupportsIndex = 0, verbose: bool = False) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Lanczos(Hop: cytnx.cytnx.LinOp, Tin: cytnx.cytnx.UniTensor, which: str = 'SA', Maxiter: typing.SupportsInt | typing.SupportsIndex = 10000, CvgCrit: typing.SupportsFloat | typing.SupportsIndex = 0, k: typing.SupportsInt | typing.SupportsIndex = 1, is_V: bool = True, ncv: typing.SupportsInt | typing.SupportsIndex = 0, verbose: bool = False) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Lanczos_Exp(Hop: cytnx.cytnx.LinOp, v: cytnx.cytnx.UniTensor, tau: typing.SupportsFloat | typing.SupportsIndex, CvgCrit: typing.SupportsFloat | typing.SupportsIndex = 1e-14, Maxiter: typing.SupportsInt | typing.SupportsIndex = 10000, verbose: bool = False) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def Lanczos_Exp(Hop: cytnx.cytnx.LinOp, v: cytnx.cytnx.UniTensor, tau: complex | typing.SupportsComplex | typing.SupportsFloat | typing.SupportsIndex, CvgCrit: typing.SupportsFloat | typing.SupportsIndex = 1e-14, Maxiter: typing.SupportsInt | typing.SupportsIndex = 10000, verbose: bool = False) -> cytnx.cytnx.UniTensor:
    ...
def Lstsq(A: cytnx.cytnx.Tensor, b: cytnx.cytnx.Tensor, rcond: typing.SupportsFloat | typing.SupportsIndex = -1.0) -> list[cytnx.cytnx.Tensor]:
    ...
def Matmul(T1: cytnx.cytnx.Tensor, T2: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
def Matmul_dg(T1: cytnx.cytnx.Tensor, T2: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
def Max(Tn: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
def Min(Tn: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Norm(T1: cytnx.cytnx.UniTensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Norm(T1: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
def Outer(T1: cytnx.cytnx.Tensor, T2: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Pow(Tin: cytnx.cytnx.UniTensor, p: typing.SupportsFloat | typing.SupportsIndex) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def Pow(Tin: cytnx.cytnx.Tensor, p: typing.SupportsFloat | typing.SupportsIndex) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Pow_(Tin: cytnx.cytnx.UniTensor, p: typing.SupportsFloat | typing.SupportsIndex) -> None:
    ...
@typing.overload
def Pow_(Tin: cytnx.cytnx.Tensor, p: typing.SupportsFloat | typing.SupportsIndex) -> None:
    ...
@typing.overload
def Qdr(Tio: cytnx.cytnx.UniTensor, is_tau: bool = False) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Qdr(Tio: cytnx.cytnx.Tensor, is_tau: bool = False) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Qr(Tio: cytnx.cytnx.UniTensor, is_tau: bool = False) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Qr(Tio: cytnx.cytnx.Tensor, is_tau: bool = False) -> list[cytnx.cytnx.Tensor]:
    ...
def Rand_isometry(Tin: cytnx.cytnx.Tensor, keepdim: typing.SupportsInt | typing.SupportsIndex, power_iteration: typing.SupportsInt | typing.SupportsIndex = 2, seed: typing.SupportsInt | typing.SupportsIndex = -1) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Rsvd(Tin: cytnx.cytnx.Tensor, keepdim: typing.SupportsInt | typing.SupportsIndex, err: typing.SupportsFloat | typing.SupportsIndex = 0.0, is_U: bool = True, is_vT: bool = True, return_err: typing.SupportsInt | typing.SupportsIndex = 0, mindim: typing.SupportsInt | typing.SupportsIndex = 1, oversampling_summand: typing.SupportsInt | typing.SupportsIndex = 10, oversampling_factor: typing.SupportsFloat | typing.SupportsIndex = 1.0, power_iteration: typing.SupportsInt | typing.SupportsIndex = 0, seed: typing.SupportsInt | typing.SupportsIndex = -1) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Rsvd(Tin: cytnx.cytnx.UniTensor, keepdim: typing.SupportsInt | typing.SupportsIndex, err: typing.SupportsFloat | typing.SupportsIndex = 0.0, is_U: bool = True, is_vT: bool = True, return_err: typing.SupportsInt | typing.SupportsIndex = 0, mindim: typing.SupportsInt | typing.SupportsIndex = 1, oversampling_summand: typing.SupportsInt | typing.SupportsIndex = 10, oversampling_factor: typing.SupportsFloat | typing.SupportsIndex = 1.0, power_iteration: typing.SupportsInt | typing.SupportsIndex = 0, seed: typing.SupportsInt | typing.SupportsIndex = -1) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Rsvd(Tin: cytnx.cytnx.UniTensor, keepdim: typing.SupportsInt | typing.SupportsIndex, min_blockdim: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], err: typing.SupportsFloat | typing.SupportsIndex = 0.0, is_U: bool = True, is_vT: bool = True, return_err: typing.SupportsInt | typing.SupportsIndex = 0, mindim: typing.SupportsInt | typing.SupportsIndex = 1, oversampling_summand: typing.SupportsInt | typing.SupportsIndex = 10, oversampling_factor: typing.SupportsFloat | typing.SupportsIndex = 1.0, power_iteration: typing.SupportsInt | typing.SupportsIndex = 0, seed: typing.SupportsInt | typing.SupportsIndex = -1) -> list[cytnx.cytnx.UniTensor]:
    ...
def Sum(Tn: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Svd(Tin: cytnx.cytnx.Tensor, is_UvT: bool = True) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Svd(Tin: cytnx.cytnx.UniTensor, is_UvT: bool = True) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Svd_truncate(Tin: cytnx.cytnx.Tensor, keepdim: typing.SupportsInt | typing.SupportsIndex, err: typing.SupportsFloat | typing.SupportsIndex = 0.0, is_UvT: bool = True, return_err: typing.SupportsInt | typing.SupportsIndex = 0, mindim: typing.SupportsInt | typing.SupportsIndex = 1) -> list[cytnx.cytnx.Tensor]:
    ...
@typing.overload
def Svd_truncate(Tin: cytnx.cytnx.UniTensor, keepdim: typing.SupportsInt | typing.SupportsIndex, err: typing.SupportsFloat | typing.SupportsIndex = 0, is_UvT: bool = True, return_err: typing.SupportsInt | typing.SupportsIndex = 0, mindim: typing.SupportsInt | typing.SupportsIndex = 1) -> list[cytnx.cytnx.UniTensor]:
    ...
@typing.overload
def Svd_truncate(Tin: cytnx.cytnx.UniTensor, keepdim: typing.SupportsInt | typing.SupportsIndex, min_blockdim: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], err: typing.SupportsFloat | typing.SupportsIndex = 0, is_UvT: bool = True, return_err: typing.SupportsInt | typing.SupportsIndex = 0, mindim: typing.SupportsInt | typing.SupportsIndex = 1) -> list[cytnx.cytnx.UniTensor]:
    ...
def Tensordot(T1: cytnx.cytnx.Tensor, T2: cytnx.cytnx.Tensor, indices_1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], indices_2: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], cacheL: bool = False, cacheR: bool = False) -> cytnx.cytnx.Tensor:
    ...
def Tensordot_dg(T1: cytnx.cytnx.Tensor, T2: cytnx.cytnx.Tensor, indices_1: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], indices_2: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], diag_L: bool) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def Trace(Tn: cytnx.cytnx.UniTensor, axisA: typing.SupportsInt | typing.SupportsIndex = 0, axisB: typing.SupportsInt | typing.SupportsIndex = 1) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def Trace(Tn: cytnx.cytnx.UniTensor, axisA: str, axisB: str) -> cytnx.cytnx.UniTensor:
    ...
@typing.overload
def Trace(Tn: cytnx.cytnx.Tensor, axisA: typing.SupportsInt | typing.SupportsIndex = 0, axisB: typing.SupportsInt | typing.SupportsIndex = 1) -> cytnx.cytnx.Tensor:
    ...
def Tridiag(A: cytnx.cytnx.Tensor, B: cytnx.cytnx.Tensor, is_V: bool = True, is_row: bool = False, throw_excp: bool = False) -> list[cytnx.cytnx.Tensor]:
    ...
def Vectordot(T1: cytnx.cytnx.Tensor, T2: cytnx.cytnx.Tensor, is_conj: bool = False) -> cytnx.cytnx.Tensor:
    ...
@typing.overload
def norm(T1: cytnx.cytnx.UniTensor) -> float:
    ...
@typing.overload
def norm(T1: cytnx.cytnx.Tensor) -> float:
    ...
