"""
quantum gates.
"""
from __future__ import annotations
import cytnx.cytnx
import typing
__all__: list[str] = ['cntl_gate_2q', 'hadamard', 'pauli_x', 'pauli_y', 'pauli_z', 'phase_shift', 'sqrt_swap', 'swap', 'toffoli']
def cntl_gate_2q(gate_1q: cytnx.cytnx.UniTensor) -> cytnx.cytnx.UniTensor:
    ...
def hadamard(device: typing.SupportsInt | typing.SupportsIndex = -1) -> cytnx.cytnx.UniTensor:
    ...
def pauli_x(device: typing.SupportsInt | typing.SupportsIndex = -1) -> cytnx.cytnx.UniTensor:
    ...
def pauli_y(device: typing.SupportsInt | typing.SupportsIndex = -1) -> cytnx.cytnx.UniTensor:
    ...
def pauli_z(device: typing.SupportsInt | typing.SupportsIndex = -1) -> cytnx.cytnx.UniTensor:
    ...
def phase_shift(phase: typing.SupportsFloat | typing.SupportsIndex, device: typing.SupportsInt | typing.SupportsIndex = -1) -> cytnx.cytnx.UniTensor:
    ...
def sqrt_swap(device: typing.SupportsInt | typing.SupportsIndex = -1) -> cytnx.cytnx.UniTensor:
    ...
def swap(device: typing.SupportsInt | typing.SupportsIndex = -1) -> cytnx.cytnx.UniTensor:
    ...
def toffoli(device: typing.SupportsInt | typing.SupportsIndex = -1) -> cytnx.cytnx.UniTensor:
    ...
