{% set data = load_file_data('pyproject.toml') %}
{% set version = data.get('project').get('version') %}

package:
  name: cytnx
  version: {{ version }}

source:
  path: ../../

build:
  number: 0
  script_env:
    # Refer to : https://github.com/ccache/ccache/discussions/821#discussioncomment-521209
    - CCACHE_NOHASHDIR=1
    - CCACHE_COMPILERCHECK=content
    - CCACHE_DIR
    - CCACHE_MAXSIZE
    - CMAKE_C_COMPILER_LAUNCHER
    - CMAKE_CXX_COMPILER_LAUNCHER
    - CMAKE_CUDA_COMPILER_LAUNCHER

requirements:
  build:
    - ccache
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - scikit-build-core
    - pybind11
    - boost >=1.82.0
    - blas=*=openblas
    - gtest
    - arpack
  run:
    - python
    - numpy >=1.18
    - boost >=1.82.0
    - python-graphviz
    - graphviz
    - blas=*=openblas
    - beartype
    - arpack

test:
  requires:
    - gtest
