package:
  name: cytnx
  version: "0.9.1"

source:
  git_url: https://github.com/kaihsin/Cytnx.git

build:
  number: 0


requirements:
  build:
    - "python {{ python }}"
    - "numpy >=1.18"
    - "cmake"
    - "make"
    - "pybind11"
    - "boost"
    - "libboost"
    - "mkl >=2019"
    - "mkl-include >=2019"
    - "llvm-openmp"
    - "setuptools"
    - "python-graphviz"
    - "graphviz"
    - "blas * mkl"
    - "{{ compiler(\"c\")}}"
    - "{{ compiler(\"cxx\")}}"

  host:
    - "python"
    - "numpy >=1.18"
    - "boost"
    - "libboost"
    - "make"
    - "mkl >=2019"
    - "mkl-include >=2019"
    - "mkl-service"
    - "llvm-openmp"
    - "setuptools"
    - "python-graphviz"
    - "graphviz"
    - "blas * mkl"
    - "{{ compiler(\"c\")}}"
    - "{{ compiler(\"cxx\")}}"

  run:
    - "python"
    - "numpy >=1.18"
    - "boost"
    - "libboost"
    - "mkl >=2019"
    - "mkl-include >=2019"
    - "mkl-service"
    - "llvm-openmp"
    - "setuptools"
    - "python-graphviz"
    - "graphviz"
    - "blas * mkl"
    - "cmake"
    - "make"
    - "pybind11"
    - "{{ compiler(\"c\")}}"
    - "{{ compiler(\"cxx\")}}"

about:
