{% set data = load_setup_py_data() %}
{% set version = data.get('version') %}

package:
  name: cytnx
  version: {{ version }}

source:
  path: ../../

build:
  number: 0


requirements:
  build:
    - "python {{ python }}"
    - "numpy >=1.18"
    - "cmake"
    - "make"
    - "pybind11"
    - "boost"
    # - "libboost"
    - "mkl >=2019"
    - "mkl-include >=2019"
    - "llvm-openmp"
    - "setuptools"
    - "python-graphviz"
    - "graphviz"
    - "blas * mkl"
    - "beartype"
    - "gtest"
    - '{{ compiler("c")}}'
    - '{{ compiler("cxx")}}'

  host:
    - "python"
    - "numpy >=1.18"
    - "boost"
    # - "libboost"
    - "make"
    - "mkl >=2019"
    - "mkl-include >=2019"
    - "mkl-service"
    - "llvm-openmp"
    - "setuptools"
    - "python-graphviz"
    - "graphviz"
    - "blas * mkl"
    - "beartype"
    - "gtest"
    - '{{ compiler("c")}}'
    - '{{ compiler("cxx")}}'

  run:
    - "python"
    - "numpy >=1.18"
    - "boost"
    # - "libboost"
    - "mkl >=2019"
    - "mkl-include >=2019"
    - "mkl-service"
    - "llvm-openmp"
    - "setuptools"
    - "python-graphviz"
    - "graphviz"
    - "blas * mkl"
    - "beartype"
    - "gtest"
    - "cmake"
    - "make"
    - "pybind11"
    - '{{ compiler("c")}}'
    - '{{ compiler("cxx")}}'

about:
