[project]
name = "cytnx-doc"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Kai", email = "kaihsinwu@gmail.com" }
]
dependencies = [
    "sphinx>=8.0.2",
    "sphinxcontrib-bibtex>=2.6.2",
    "breathe>=4.35.0",
    "sphinxcontrib-jquery>=4.1",
    "sphinxbootstrap4theme>=0.6.0",
    "setuptools>=72.1.0",
    "sphinx-multiversion>=0.2.4",
]
readme = "README.md"
requires-python = ">= 3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/cytnx_doc"]

[tool.uv]
dev-dependencies = [
    "rust-just>=1.36.0",
]

