# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget Cytnx::cytnx)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target Cytnx::cytnx
add_library(Cytnx::cytnx STATIC IMPORTED)

set_target_properties(Cytnx::cytnx PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_std_11"
  INTERFACE_INCLUDE_DIRECTORIES "/home/kaywu/Dropbox/Cytnx/include"
  INTERFACE_LINK_LIBRARIES "Boost::boost;/home/kaywu/.pyenv/versions/anaconda3-5.3.1/lib/libmkl_intel_ilp64.so;/home/kaywu/.pyenv/versions/anaconda3-5.3.1/lib/libmkl_intel_thread.so;/home/kaywu/.pyenv/versions/anaconda3-5.3.1/lib/libmkl_core.so;/usr/lib/x86_64-linux-gnu/libiomp5.so;-lpthread;-lm;-ldl;/usr/local/cuda/lib64/libcusolver.so;\$<LINK_ONLY:-lcublas>;\$<LINK_ONLY:-lcurand>"
)

# Import target "Cytnx::cytnx" for configuration "Release"
set_property(TARGET Cytnx::cytnx APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(Cytnx::cytnx PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CUDA;CXX"
  IMPORTED_LOCATION_RELEASE "/home/kaywu/Dropbox/Cytnx/cmake/libcytnx.a"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
