package:
  name: cytnx_37
  version: "0.5.3a"

source:
  path: ../

build:
  noarch: generic
  number: 0


requirements:
  build:
    - python 3.7
    - numpy >=1.18
    - cmake  
    - pybind11 
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - graphviz
    - blas * mkl
    - python-graphviz
    - {{ compiler("c")}}
    - {{ compiler("cxx")}}

  host:
    - python 3.7
    - boost
    - numpy >=1.18
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - setuptools
    - graphviz
    - blas * mkl
    - python-graphviz

  run:
    - python 3.7
    - boost
    - mkl >=2019
    - mkl-include >=2019
    - intel-openmp
    - numpy >=1.18
    - setuptools
    - python-graphviz
    - graphviz
    - blas * mkl
    - python-graphviz

about:
