name: CMake Tests

on: [push]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        $CONDA/bin/conda config --add channels conda-forge
        $CONDA/bin/conda install python=3.10 _openmp_mutex=*=*_llvm
        $CONDA/bin/conda upgrade --all
        $CONDA/bin/conda install cmake make boost libboost git compilers numpy mkl mkl-include mkl-service pybind11 libblas=*=*mkl

    - name: Configure CMake
      run: $CONDA/bin/cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build -DCMAKE_INSTALL_PREFIX=/home/petjelinux/Cytnx_lib -DUSE_MKL=on -DUSE_HPTT=on -DHPTT_ENABLE_FINE_TUNE=on -DHPTT_ENABLE_AVX=on -DBUILD_PYTHON=on -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DRUN_TESTS=on

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: $CONDA/bin/cmake --build .

    - name: Run CTest
      working-directory: ${{runner.workspace}}/build
      run: GTEST_COLOR=1 ctest --output-junit junit.xml

    #- name: Upload test results
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: test_results_xml
    #    path: ${{runner.workspace}}/build/test-results/**/*.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        #directory: ${{runner.workspace}}/build/test-results/
        file: ${{runner.workspace}}/build/junit.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
        path_to_write_report: ./converage/codecov_report.txt
