name: CMake Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        conda config --add channels conda-forge
        conda create --name cytnx python=3.10 _openmp_mutex=*=*_llvm
        conda activate cytnx
        conda upgrade --all
        conda install cmake make boost libboost git compilers numpy mkl mkl-include mkl-service pybind11 libblas=*=*mkl

    - name: Configure CMake
      run: cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build -DCMAKE_INSTALL_PREFIX=/home/petjelinux/Cytnx_lib -DUSE_MKL=on -DUSE_HPTT=on -DHPTT_ENABLE_FINE_TUNE=on -DHPTT_ENABLE_AVX=on -DBUILD_PYTHON=on -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DRUN_TESTS=on

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build .

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: GTEST_OUTPUT=xml:test-results/ GTEST_COLOR=1 ctest -V

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results_xml
        path: ${{runner.workspace}}/build/test-results/**/*.xml
