name: CMake Tests

on: [push]

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        $CONDA/bin/conda config --add channels conda-forge
        $CONDA/bin/conda install python=3.10 _openmp_mutex=*=*_llvm
        $CONDA/bin/conda upgrade --all
        $CONDA/bin/conda install cmake make boost libboost git compilers numpy mkl mkl-include mkl-service pybind11 libblas=*=*mkl

    - name: Configure CMake
      run: $CONDA/bin/cmake -S $GITHUB_WORKSPACE -B ${{runner.workspace}}/build -DCMAKE_INSTALL_PREFIX=/home/petjelinux/Cytnx_lib -DUSE_MKL=on -DUSE_HPTT=on -DHPTT_ENABLE_FINE_TUNE=on -DHPTT_ENABLE_AVX=on -DBUILD_PYTHON=on -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DRUN_TESTS=on

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: $CONDA/bin/cmake --build . -j `nproc`

    - name: Run CTest
      working-directory: ${{runner.workspace}}/build
      run: GTEST_COLOR=1 ctest --output-junit /home/runner/junit.xml

    #- name: Upload test results
    #  uses: actions/upload-artifact@v3
    #  with:
    #    name: test_results_xml
    #    path: ${{runner.workspace}}/build/test-results/**/*.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        #token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        #directory: ${{runner.workspace}}/build
        files: /home/runner/junit.xml # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
        version: "v0.1.15"

    - name: Download Coverity Build Tool
      working-directory: ${{runner.workspace}}/build
      run: |
        wget -q https://scan.coverity.com/download/cxx/linux64 --post-data "token=$TOKEN&project=kaihsin%2FCytnx" -O cov-analysis-linux64.tar.gz
        mkdir cov-analysis-linux64
        tar xzf cov-analysis-linux64.tar.gz --strip 1 -C cov-analysis-linux64
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}

    - name: Build with cov-build
      working-directory: ${{runner.workspace}}/build
      run: |
        export PATH=`pwd`/cov-analysis-linux64/bin:$PATH
        cov-build --dir cov-int $CONDA/bin/cmake --build . -j `nproc`

    - name: Submit the result to Coverity Scan
      working-directory: ${{runner.workspace}}/build
      run: |
        tar czvf cytnx.tgz cov-int 
        curl \
          --form token=$TOKEN \
          --form email=jeffry1829@gmail.com \
          --form file=@cytnx.tgz \
          --form version="v0.7.5" \
          --form description="Cytnx" \
          https://scan.coverity.com/builds?project=kaihsin%2FCytnx
      env:
        TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
