name: Conda Build For MacOSX (Test build)

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:


jobs:
  BuildAndTest:
    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        # Specify python version your environment will have. Remember to quote this, or
        # YAML will think you want python 3.1 not 3.10
        python-version: "3.10"
        # This uses *miniforge*, rather than *minicond*. The primary difference is that
        # the defaults channel is not enabled at all
        miniforge-version: latest
        # These properties enable the use of mamba, which is much faster and far less error
        # prone than conda while being completely compatible with the conda CLI
        use-mamba: true
        mamba-version: "*"

    - name: Config Conda
      working-directory: ${{github.workspace}}
      shell: bash -l {0}
      run: |
        echo "Config Conda---------------------------------"
        mamba install anaconda-client boa -c conda-forge


    - name: start building
      working-directory: ${{github.workspace}}
      shell: bash -l {0}
      run: |
        echo "Building begin---------------------------------"
        conda config --set anaconda_upload no

        # these are infos used to check environ
        mamba info -a
        mamba list
        mamba -h

        echo "Get Output file names:_________________"
        # OUTPUT_FN=$(conda build conda_build/conda_gen_mac/ --output)

        echo "Start building---------------------------------"
        conda mambabuild conda_build/conda_gen_mac/


      env:
        TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
