name: Conda Build For Linux (Release)

on:
  push:
    tags:
     - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v2
      with:
        # Specify python version your environment will have. Remember to quote this, or
        # YAML will think you want python 3.1 not 3.10
        python-version: "3.11"
        # This uses *miniforge*, rather than *minicond*. The primary difference is that
        # the defaults channel is not enabled at all
        miniforge-version: latest
        # These properties enable the use of mamba, which is much faster and far less error
        # prone than conda while being completely compatible with the conda CLI
        use-mamba: true
        mamba-version: "*"

    - name: Config Conda
      working-directory: ${{github.workspace}}
      shell: bash -l {0}
      run: |
        echo "Config Conda---------------------------------"
        mamba install anaconda-client boa -c conda-forge

    - name: start building
      working-directory: ${{github.workspace}}
      shell: bash -l {0}
      run: |
        echo "Building begin---------------------------------"
        conda config --set anaconda_upload no

        # these are infos used to check environ
        mamba list


        echo "Get Output file names:_________________"
        OUTPUT_FN=$(conda build conda_build/conda_gen/ --output)

        echo $OUTPUT_FN
        #echo $TOKEN

        echo "Start building---------------------------------"
        conda mambabuild conda_build/conda_gen/

        echo "Upload build---------------------------------"
        #echo $OUTPUT_FN

        anaconda -t $TOKEN upload -u kaihsinwu $OUTPUT_FN --force

      env:
        TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
