name: Conda Build For MacOSX (Test build)

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:


jobs:
  BuildAndTest:
    runs-on: macos-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v3
      with:
        # Remember to quote this, or YAML will think you want python 3.1 not 3.10
        python-version: "3.10"
        # Using miniforge to the enable conda-forge channel only.
        miniforge-version: latest
    - name: Config Conda
      shell: bash -l {0}
      run: |
        echo "Config Conda---------------------------------"
        conda info
        conda config --set anaconda_upload no
        conda install conda-build
    - name: start building
      shell: bash -l {0}
      # TODO: Consider to replace conda-build with rattler-build to speed up
      #   the build process.
      run: |
        echo "Start building---------------------------------"
        conda build conda_build/conda_gen_mac/

      env:
        TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
