name: Conda Build (Release)

on:
  push:
    tags:
     - 'v[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  BuildAndTest:
    name: BuildAndTest-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - uses: conda-incubator/setup-miniconda@v3
      with:
        # Remember to quote this, or YAML will think you want python 3.1 not 3.10
        python-version: "3.10"
        # Using miniforge to the enable conda-forge channel only.
        miniforge-version: latest

    - name: Config Conda
      run: |
        echo "Config Conda---------------------------------"
        conda info
        conda config --set anaconda_upload no
        conda install conda-build

    - name: Cache Ccache Directory
      uses: actions/cache@v4
      with:
        path: |
          ~/.ccache
        key: ccache-${{ runner.os }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          ccache-${{ runner.os }}-${{ github.ref_name }}-

    - name: start building
      # TODO: Consider to replace conda-build with rattler-build to speed up
      #   the build process.
      # Conda build creates different working folder each time, which make
      # ccache fails to hit the cache. Set `--build-id-pat` to make the build
      # folder consistent across builds, so that ccache can hit the cache.
      # See: https://github.com/ccache/ccache/discussions/821#discussioncomment-521209
      run: |
        echo "Building begin---------------------------------"
        export CCACHE_DIR="${HOME}/.ccache"

        echo "Get Output filename_________________"
        OUTPUT_FN=$(conda build conda_build/ --build-id-pat "cytnx" --output)
        echo $OUTPUT_FN

        echo "Start building---------------------------------"
        conda build conda_build/ --build-id-pat "cytnx"

        echo "Upload build---------------------------------"
        anaconda -t $TOKEN upload -u kaihsinwu "$OUTPUT_FN" --force

      env:
        CMAKE_C_COMPILER_LAUNCHER: ccache
        CMAKE_CXX_COMPILER_LAUNCHER: ccache
        CMAKE_CUDA_COMPILER_LAUNCHER: ccache
        # DO NOT enable this line because the script for conda build is not
        # executed in a interactive shell, and "~" will not be expanded to the
        # home directory. Export CCACHE_DIR in the run command instead.
        # CCACHE_DIR: ~/.ccache
        CCACHE_MAXSIZE: 1G  # The limit of actions/cache is 10GB
        TOKEN: ${{ secrets.CONDA_UPLOAD_TOKEN }}
